# python gen_traverse.py --model-num 1 --save-dir "ablation2/test"
# python gen_traverse.py --model-num 2 --save-dir "ablation2/test"
# python gen_traverse.py --model-num 3 --save-dir "ablation2/test"
# python gen_traverse.py --model-num 4 --save-dir "ablation2/test"
# python gen_traverse.py --model-num 5 --save-dir "ablation2/test"
# python gen_traverse.py --model-num 6 --save-dir "ablation2/test"
# python gen_traverse.py --model-num 7 --save-dir "ablation2/test"
# python gen_traverse.py --model-num 8 --save-dir "ablation2/test"
# python gen_traverse.py --model-num 9 --save-dir "ablation2/test"
python gen_traverse.py --model-num 10 --save-dir "ablation2_best/test"
python gen_traverse.py --model-num 11 --save-dir "ablation2_best/test"
python gen_traverse.py --model-num 12 --save-dir "ablation2_best/test"